import model.*

fun main() {
    try {
        //Run any function within this try catch block
    }catch (e: Exception){
        println(e.message)
    }
}